If you look at the assertion it's saying that you've declared the same
SimObject twice.  One could easily argue that this isn't an error, but
we figured that it would reduce the chances of someone messing up.  Do
you create a subclass of something and call it BaseCPU in your script?
 Can you attach your script?
  Nate
- Show quoted text -
On Sat, Mar 15, 2008 at 4:46 PM, Ashutosh Jain <ashujain7@gmail.com> wrote:
> hi
>
> while running M5 spec cpu 2000 i am getting error ............
>
>
> [ashutoshj@kani example]$ ../../build/ALPHA_SE/m5.opt runshort.py
> M5 Simulator System
> Copyright (c) 2001-2006
> The Regents of The University of Michigan
> All Rights Reserved
>
> M5 compiled Mar 13 2008 02:14:30
> M5 started Sat Mar 15 18:32:26 2008
> M5 executing on kani.cs.lamar.edu
> command line: ../../build/ALPHA_SE/m5.opt runshort.py
> Traceback (most recent call last):
>    File "<string>", line 1, in ?
>   File "build/ALPHA_SE/python/m5/main.py", line 350, in main
>   File "runshort.py", line 5, in ?
>     from DetailedUniConfig import *
>   File "/space/ashutoshj/m5_2.0b4/configs/test/DetailedUniConfig.py", line
> 7, in ?
>      from FullCPU import *
>   File "/space/ashutoshj/m5_2.0b4/configs/test/FullCPU.py", line 4, in ?
>     from BaseCPU import BaseCPU
>   File "/space/ashutoshj/m5_2.0b4/configs/test/BaseCPU.py", line 4, in ?
>      class BaseCPU(SimObject):
>   File "build/ALPHA_SE/python/m5/SimObject.py", line 143, in __new__
> AssertionError
> [ashutoshj@kani example]$
>
>
> What is this Assertion Error and how to overcome this.............Please
> help
>
>
> Thanks in advance
>
>
> --
> Ashutosh Jain
> M.S. Computer Science
>
> _______________________________________________
>  m5-users mailing list
>  m5-users@m5sim.org
>  http://m5sim.org/cgi-bin/mailman/listinfo/m5-users
>
_______________________________________________
m5-users mailing list
m5-users@m5sim.org
http://m5sim.org/cgi-bin/mailman/listinfo/m5-users
